name: CI/CD CalJS

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ssgs-calc
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
      - name: Installa dipendenze
        run:  npm install
      - run: npm run build
      - name: Esegue i test
        run: npm test
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ssgs-calc/coverage


      
  
